### PR TITLE
Add Milkshakes and Shirley Temples

### PR DESCRIPTION
**Pull request by MitztheKat**
Pretty simple. I'm a bit new to coding and this is my first pull request sooo

## About The Pull Request
Adding 2 new drinks to the game so I have a valid reason to invade the bartender's space to teach him how to make it.

## Why It's Good For The Game
Makes our server unique with 2 new drinks to make.

## Changelog
:cl:
add: Adds the Shirley Temple, and the Milkshake. Shirley is similar to tequilla, and the milkshake is a gibbfloat but milk.
:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
You shouldn't PR from master. Instead, you should create new branch, name it something related to what you're coding, code it on the branch and PR that. Rrefer to the screenshot to see what I'm talking about:
https://cdn.discordapp.com/attachments/783449504782221312/783449712152936488/Screenshot_704.png

**Comment by EgorDinamit** [comment]
I'd suggest creating a new .dm file for server-specific drinks, to avoid merge conflicts.

**Comment by MitztheKat** [comment]
I can do that, i just need some time. might take a day or two depending if i have time today.

**Comment by MitztheKat** [comment]
gonna try a different pull request, hang on. It has it in a different file/folder.

**Pull request closed without merging**
